# Chapter 1: What is EDA?

Exploratory Data Analysis (EDA) is the very first thing you do when you get a dataset. Before building any model, before running any statistics — you explore the data. Think of it like a detective inspecting a crime scene before drawing any conclusions.

The term was coined by statistician **John Tukey in 1977**. His idea was simple:
> *"Let the data speak to you before you force a theory on it."*

In plain language — EDA answers questions like:

-  What does this data look like?
-  Is anything missing or broken?
-  Are there patterns, trends, outliers?
-  What are the relationships between variables?

---

> *"Let me show you the big picture first:"*

##  The Big Picture of EDA

| Step | Name | Details |
|------|------|---------|
| 1️ | **Load Data** | Read CSV, Excel, DB |
| 2️ | **First Inspection** | shape, dtypes, info |
| 3️ | **Data Quality** | nulls, duplicates |
| 4️ | **Univariate** | 1 variable at a time |
| 5️ | **Bivariate** | 2 variables together |
| 6️ | **Multivariate** | many variables |
| 7️ | **Visualize** | plots, charts, heatmaps |
| 8️ | **Insights** | patterns, hypotheses |
| 9️ | **Feature Eng.** | prepare for models |

>  Flow: Load → Inspect → Quality → Univariate → Bivariate → Multivariate → Visualize → Insights → Feature Eng.

In [4]:
# in this notebook we cover step (1) and (2 ) i.e
# 1.Load data and 2.First inspection

# Chapter 2:Types of Data

Before touching any code you must understand 3 types of data

# Types of Data

**Data** branches into 3 types:

| Type | Description | Sub-types / Examples |
|------|-------------|----------------------|
| **Numerical** | Numbers with meaning | ↳ **Continuous** (height, salary) <br> ↳ **Discrete** (age, count) |
| **Categorical** | Groups, labels | *(no math on these!)* |
| **Ordinal** | Ordered categories | Low < Med < High, 1 – 5 |

---

###  Numerical
- **Continuous** → height, salary *(any value in a range)*
- **Discrete** → age, count *(only whole numbers)*

###  Categorical
- Groups or labels → gender, city, color
-  **No math operations allowed!**

###  Ordinal
- Ordered categories → Low < Medium < High
- Rating scales → 1 to 5

## Understanding Each Data Type

---

###  Numerical — *"Math makes sense here"*
Numbers you can add, subtract, average.

> **Example:** Employee salaries → ₹45,000 | ₹72,000 | ₹1,20,000

| Subtype | Definition | Example |
|---------|------------|---------|
| **Continuous** | Any value in a range | Height = 5.73 ft |
| **Discrete** | Whole counts only | No. of children = 0, 1, 2 |

---

###  Categorical — *"Just labels, no math"*
Groups or names. You **cannot** perform math on them.

> **Examples:**
> - Gender → Male / Female / Other
> - City → Mumbai / Delhi / Hyderabad
> - Product → Electronics / Clothing

>  Male + Female ≠ anything meaningful!

---

###  Ordinal — *"Order matters, but gaps don't"*
Categories with a **natural order**, but unequal gaps between them.

> **Example 1 — Customer Satisfaction:**
> Very Bad → Bad → Neutral → Good → Excellent
> *(You know Excellent > Good, but not by how much)*

> **Example 2 — Education Level:**
> 10th < 12th < Graduate < Postgraduate

##  Chapter 3: Pandas Data Types

In Python's **pandas**, every column has a specific data type.
This matters because pandas **behaves differently** depending on the type.

---

###  Common Pandas Data Types

| Pandas dtype | Meaning | Example |
|-------------|---------|---------|
| `int64` | Whole numbers | age = 25, count = 3 |
| `float64` | Decimal numbers | salary = 45000.50 |
| `object` | Text / strings | name = "Sai", city = "Hyderabad" |
| `bool` | True / False | is_active = True |
| `datetime64` | Dates & times | 2024-01-01 |
| `category` | Categorical labels | gender, product type |

---

###  Critical line — int becomes float!

> When a column has **even one missing value**, pandas upgrades `int64` → `float64`
> because `NaN` is technically a **float** in Python.


>  We'll handle missing values in the **next session**.

# Chapter 4: Loading Data & First Inspection
Let's write real code. We'll use the famous Titanic dataset — it has numerical, categorical, ordinal, and datetime-like columns all in one place. Perfect for learning.

## Step 1 - Install and Import

In [11]:
# always start with imports
import pandas as pd       # the core data manipulation library
import numpy as np        # for numerical operations

# if you don't have pandas installed, run this in terminal:
# pip install pandas

## Step 2 - load the data

In [ ]:
# Method 1: Load from a CSV file on your computer
df = pd.read_csv('titanic.csv')

# Method 2: Load directly from the internet (Titanic dataset)
url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
df = pd.read_csv(url)

# Method 3: Load from Excel
df = pd.read_excel('sales_data.xlsx')

# Method 4: Load from a database (SQL)
import sqlite3
conn = sqlite3.connect('my_database.db')
df = pd.read_sql('SELECT * FROM customers', conn)

In [14]:
import os , sys
sys.path.append(os.path.abspath('..'))

In [16]:
df = pd.read_csv('../data/titanic.csv')

## Step 3 — The 5 Essential First Inspection Commands
Here's where the real learning begins. Run these commands in this exact order every time you get a new dataset:

## 3.1 — df.shape → "How big is this data?"

In [20]:
print(df.shape)  # shape is a tuple so it works even if u dont write print

(891, 12)

## 3.2 — df.head() and df.tail()

In [22]:
df.head() # first 5

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [23]:
df.tail() # last 5

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [25]:
df.head(1)# u can also mention in paranthesis for how many u want

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S

In [26]:
df.tail(1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

## 3.3 — df.dtypes

In [27]:
print(df.dtypes)

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

## 3.4 — df.info()

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

## 3.5 — df.describe()

In [29]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [30]:
df.describe(include = 'object')

                           Name   Sex  Ticket Cabin Embarked
count                       891   891     891   204      889
unique                      891     2     681   147        3
top     Braund, Mr. Owen Harris  male  347082    G6        S
freq                          1   577       7     4      644

In [31]:
df.describe(include = 'all')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,891.000000,891.000000,891.000000,891,891,714.000000,891.000000,891.000000,891,891.000000,204,889
unique,NaN,NaN,NaN,891,2,NaN,NaN,NaN,681,NaN,147,3
top,NaN,NaN,NaN,"Braund, Mr. Owen Harris",male,NaN,NaN,NaN,347082,NaN,G6,S
freq,NaN,NaN,NaN,1,577,NaN,NaN,NaN,7,NaN,4,644
mean,446.000000,0.383838,2.308642,NaN,NaN,29.699118,0.523008,0.381594,NaN,32.204208,NaN,NaN
std,257.353842,0.486592,0.836071,NaN,NaN,14.526497,1.102743,0.806057,NaN,49.693429,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,0.420000,0.000000,0.000000,NaN,0.000000,NaN,NaN
25%,223.500000,0.000000,2.000000,NaN,NaN,20.125000,0.000000,0.000000,NaN,7.910400,NaN,NaN
50%,446.000000,0.000000,3.000000,NaN,NaN,28.000000,0.000000,0.000000,NaN,14.454200,NaN,NaN
75%,668.500000,1.000000,3.000000,NaN,NaN,38.000000,1.000000,0.000000,NaN,31.000000,NaN,NaN
max,891.000000,1.000000,3.000000,NaN,NaN,80.000000,8.000000,6.000000,NaN,512.329200,NaN,NaN

### putting it all together

In [ ]:
import pandas as pd
import numpy as np

# Load data
df = pd.read_csv('your_data.csv')

# first inspection

print("SHAPE:", df.shape)

print(df.head())

print(df.tail())

print(df.dtypes)

print(df.info())


print(df.describe())

print("=" * 50)
print("missing colummns:")
print(df.isnull().sum())  # Bonus

# END of notebook 1